package risco.vistas;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;

import javafx.scene.image.ImageView;

public class riscoController {
	@FXML
	private MenuItem exportar;
	@FXML
	private MenuItem importar;
	@FXML
	private MenuItem ayuda;
	@FXML
	private TextField Jugador;
	@FXML
	private ImageView imgDado1;
	@FXML
	private ImageView imgDado2;
	@FXML
	private ImageView imgDado3;

	// Event Listener on Button.onAction
	@FXML
	public void TirarDados(ActionEvent event) {
		// TODO Autogenerated
	}
}
